source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'
use_frameworks!

target 'SampleiOS' do
 	pod 'sdk-objectmodel-swift', '~> 0.1.3-beta.0'
    pod 'sdk-core-swift', '~> 0.1.6-beta.4'
    pod 'XyBleSdk', '~> 0.0.1'
    pod 'sdk-xyobleinterface-swift', :path => '../'
    
end

   

